name: Watch TLDs changes daily

on:
  schedule:
  - cron: '*/5 * * * *'

jobs:
  tlds_watch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Download TLDs file
      run: curl -s "https://data.iana.org/TLD/tlds-alpha-by-domain.txt" | tail -n +2 >tlds.txt
    - name: Commit files
      run: |
        git config --local user.email "alex@furculita.net"
        git config --local user.name "Furculita Alexandru"
        git commit -m "TLD changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
